version: '3.6'
    
services:
  # Mensjeria
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672' #The standard AMQP protocol port
      - '15672:15672' #HTTP management UI
    environment:
      AMQP_URL: 'amqp;//rabbitmq?connection_attempts=5&retry_delay=5'
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    healthcheck:
      test: rabbitmqctl status || exit 1
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 40s
  
  # Servicios de Propiedades de los Alpes
  propiedadesalpes:
    build: .
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "5001:5000"
  